# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQ', models.CharField(max_length=15, verbose_name='QQ\u53f7')),
                ('NickName', models.CharField(max_length=30, verbose_name='QQ\u6635\u79f0')),
                ('UserType', models.CharField(choices=[('\u9ed1\u540d\u5355', '\u9ed1\u540d\u5355'), ('\u767d\u540d\u5355', '\u767d\u540d\u5355'), ('\u672a\u5f52\u6863', '\u672a\u5f52\u6863')], default=('\u672a\u5f52\u6863', '\u672a\u5f52\u6863'), max_length=50, verbose_name='\u7528\u6237\u7c7b\u578b')),
            ],
            options={
                'verbose_name': 'QQ\u7ba1\u7406\u8868',
                'verbose_name_plural': 'QQ\u7ba1\u7406\u8868',
            },
        ),
    ]
